import argparse
import shutil
import subprocess
from datetime import date
from pathlib import Path

import pandas as pd


def parse_thresholds(raw: str) -> list[float]:
    vals: list[float] = []
    for part in raw.split(","):
        part = part.strip()
        if not part:
            continue
        vals.append(float(part))
    if not vals:
        raise ValueError("No thresholds provided")
    return vals


def threshold_tag(v: float) -> str:
    return str(v).replace(".", "p")


def run_panel_build(event_pool_csv: Path, model_name: str, threshold: float) -> None:
    cmd = [
        "python",
        "analysis/build_top10_panel_dataset.py",
        "--event-pool-csv",
        str(event_pool_csv),
        "--retrieval-mode",
        "hybrid",
        "--semantic-min-similarity",
        str(threshold),
        "--semantic-model-name",
        model_name,
    ]
    subprocess.run(cmd, check=True)


def collect_kept_stats(by_event_dir: Path, allowed_event_ids: set[str]) -> tuple[pd.DataFrame, dict]:
    rows = []
    for fp in sorted(by_event_dir.glob("event_*_retrieval_ranked_*.csv")):
        df = pd.read_csv(fp)
        if df.empty:
            continue
        kept = df[df["kept_by_similarity"] == 1].copy()
        event_id = str(df["event_id"].iloc[0])
        if event_id not in allowed_event_ids:
            continue
        event_title = str(df["event_title"].iloc[0])
        kept_hours = int(pd.to_datetime(kept["datetime_utc"], errors="coerce").dt.floor("h").nunique()) if len(kept) else 0
        rows.append(
            {
                "event_id": event_id,
                "event_title": event_title,
                "kept_news_count": int(len(kept)),
                "kept_news_hours": kept_hours,
                "total_candidates": int(len(df)),
                "kept_ratio": float(len(kept) / len(df)) if len(df) else 0.0,
            }
        )

    event_df = pd.DataFrame(rows)
    if event_df.empty:
        event_df = pd.DataFrame(
            columns=["event_id", "event_title", "kept_news_count", "kept_news_hours", "total_candidates", "kept_ratio"]
        )

    event_df = event_df.sort_values(["kept_news_count", "kept_news_hours", "kept_ratio"], ascending=[False, False, False])
    summary = {
        "events": int(len(event_df)),
        "events_with_kept_news": int((event_df["kept_news_count"] > 0).sum()) if len(event_df) else 0,
        "total_kept_news": int(event_df["kept_news_count"].sum()) if len(event_df) else 0,
        "total_kept_hours": int(event_df["kept_news_hours"].sum()) if len(event_df) else 0,
        "mean_kept_per_event": float(event_df["kept_news_count"].mean()) if len(event_df) else 0.0,
    }
    return event_df, summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Run layered threshold study with Qwen embedding")
    today = date.today().isoformat()
    parser.add_argument(
        "--event-pool-csv",
        default=f"result/by_date/{today}/event_pool_top10_{today}_tech.csv",
        help="Event pool csv used in threshold study",
    )
    parser.add_argument(
        "--thresholds",
        default="0.6,0.55,0.5",
        help="Comma-separated threshold list",
    )
    parser.add_argument(
        "--semantic-model-name",
        default="Qwen/Qwen3-Embedding-0.6B",
        help="Embedding model name",
    )
    args = parser.parse_args()

    thresholds = parse_thresholds(args.thresholds)
    event_pool_csv = Path(args.event_pool_csv)
    if not event_pool_csv.exists():
        raise FileNotFoundError(f"Event pool csv not found: {event_pool_csv}")

    pool_df = pd.read_csv(event_pool_csv)
    allowed_event_ids = set(pool_df["event_id"].astype(str).tolist())

    out_root = Path("result") / "by_date" / today / f"threshold_study_qwen3_{today}"
    out_root.mkdir(parents=True, exist_ok=True)

    panel_base = Path("result") / "by_date" / today
    panel_summary_path = panel_base / f"event_panel_summary_top10_{today}.csv"
    by_event_dir = panel_base / f"news_retrieval_by_event_{today}"

    result_rows = []

    for th in thresholds:
        run_panel_build(event_pool_csv=event_pool_csv, model_name=args.semantic_model_name, threshold=th)

        if not panel_summary_path.exists() or not by_event_dir.exists():
            raise RuntimeError("Expected output files were not generated by build_top10_panel_dataset.py")

        tag = threshold_tag(th)
        th_dir = out_root / f"threshold_{tag}"
        th_dir.mkdir(parents=True, exist_ok=True)

        summary_df = pd.read_csv(panel_summary_path)
        summary_out = th_dir / f"event_panel_summary_top10_{today}_th_{tag}.csv"
        summary_df.to_csv(summary_out, index=False)

        event_df, s = collect_kept_stats(by_event_dir, allowed_event_ids=allowed_event_ids)
        kept_out = th_dir / f"kept_ranking_by_event_{today}_th_{tag}.csv"
        event_df.to_csv(kept_out, index=False)

        kept_rows = []
        for fp in sorted(by_event_dir.glob("event_*_retrieval_ranked_*.csv")):
            df = pd.read_csv(fp)
            if df.empty:
                continue
            if str(df["event_id"].iloc[0]) not in allowed_event_ids:
                continue
            df = df[df["kept_by_similarity"] == 1]
            if not df.empty:
                kept_rows.append(df)
        kept_preview = pd.concat(kept_rows, ignore_index=True) if kept_rows else pd.DataFrame()
        kept_preview_out = th_dir / f"kept_news_preview_{today}_th_{tag}.csv"
        kept_preview.to_csv(kept_preview_out, index=False)

        result_rows.append(
            {
                "threshold": th,
                "events": s["events"],
                "events_with_kept_news": s["events_with_kept_news"],
                "total_kept_news": s["total_kept_news"],
                "total_kept_hours": s["total_kept_hours"],
                "mean_kept_per_event": s["mean_kept_per_event"],
                "output_dir": str(th_dir),
            }
        )

    result_df = pd.DataFrame(result_rows).sort_values("threshold", ascending=False)
    out_csv = out_root / f"threshold_study_summary_{today}.csv"
    result_df.to_csv(out_csv, index=False)

    lines = [
        "# Qwen3 分层阈值研究",
        "",
        f"- Event pool: {event_pool_csv}",
        f"- Model: {args.semantic_model_name}",
        f"- Thresholds: {thresholds}",
        "",
        result_df.to_markdown(index=False),
        "",
    ]
    out_md = out_root / f"threshold_study_summary_{today}.md"
    out_md.write_text("\n".join(lines), encoding="utf-8")

    latest_summary_copy = panel_base / f"event_panel_summary_top10_{today}_tech.csv"
    shutil.copyfile(panel_summary_path, latest_summary_copy)

    print(f"Saved threshold summary csv: {out_csv}")
    print(f"Saved threshold summary md: {out_md}")
    print(result_df.to_string(index=False))


if __name__ == "__main__":
    main()
