import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

def plot_news_price_alignment(csv_path):
    # 1. Load the aligned dataset
    try:
        df = pd.read_csv(csv_path)
    except FileNotFoundError:
        print(f"Error: {csv_path} not found. Please run the alignment script first.")
        return

    df['datetime_utc'] = pd.to_datetime(df['datetime_utc'])
    df = df.sort_values('datetime_utc')

    if df.empty:
        print("Dataset is empty. Nothing to plot.")
        return

    # Set visualization style
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, (ax1, ax3) = plt.subplots(2, 1, figsize=(15, 10), sharex=True)

    # ---------------------------------------------------------
    # Chart 1: Price vs. News Volume
    # ---------------------------------------------------------
    color_price = 'tab:blue'
    color_volume = 'tab:gray'

    ax1.set_title(f"Polymarket Price vs. News Volume Alignment", fontsize=16)
    
    # Left Y-axis: Price
    ax1.plot(df['datetime_utc'], df['price'], color=color_price, linewidth=2, label='Polymarket Price')
    ax1.set_ylabel('Market Probability (Price)', color=color_price, fontsize=12)
    ax1.tick_params(axis='y', labelcolor=color_price)
    ax1.set_ylim(0, 1.05) 

    # Right Y-axis: Volume
    ax2 = ax1.twinx()
    ax2.bar(df['datetime_utc'], df['news_volume'], color=color_volume, alpha=0.3, width=0.03, label='News Volume')
    ax2.set_ylabel('Hourly News Count', color=color_volume, fontsize=12)
    ax2.tick_params(axis='y', labelcolor=color_volume)
    ax2.grid(False) # Disable grid for the second axis to keep it clean

    # ---------------------------------------------------------
    # Chart 2: Price vs. Sentiment (Tone)
    # ---------------------------------------------------------
    color_tone = 'tab:orange'

    ax3.set_title(f"Polymarket Price vs. News Sentiment (Tone)", fontsize=16)
    
    # Left Y-axis: Price
    ax3.plot(df['datetime_utc'], df['price'], color=color_price, linewidth=2, label='Polymarket Price')
    ax3.set_ylabel('Market Probability (Price)', color=color_price, fontsize=12)
    ax3.tick_params(axis='y', labelcolor=color_price)
    ax3.set_ylim(0, 1.05)

    # Right Y-axis: Sentiment
    ax4 = ax3.twinx()
    ax4.plot(df['datetime_utc'], df['avg_tone'], color=color_tone, marker='.', linestyle='--', alpha=0.6, label='Sentiment Score (Tone)')
    ax4.axhline(0, color='red', linewidth=1, alpha=0.4, linestyle=':') # Zero line for sentiment
    ax4.set_ylabel('Avg Sentiment Score', color=color_tone, fontsize=12)
    ax4.tick_params(axis='y', labelcolor=color_tone)
    ax4.grid(False)

    # Formatting X-axis (Time)
    ax3.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:00'))
    plt.xticks(rotation=45)
    ax3.set_xlabel('Time (UTC)', fontsize=12)

    # Merging Legends for ax1 and ax2
    lines_1, labels_1 = ax1.get_legend_handles_labels()
    lines_2, labels_2 = ax2.get_legend_handles_labels()
    ax1.legend(lines_1 + lines_2, labels_1 + labels_2, loc='upper left', frameon=True)

    # Merging Legends for ax3 and ax4
    lines_3, labels_3 = ax3.get_legend_handles_labels()
    lines_4, labels_4 = ax4.get_legend_handles_labels()
    ax3.legend(lines_3 + lines_4, labels_3 + labels_4, loc='upper left', frameon=True)

    plt.tight_layout()
    
    # Save the output
    output_filename = "alignment_analysis_english.png"
    plt.savefig(output_filename, dpi=300)
    print(f"✅ Visualization complete! Chart saved as: {output_filename}")
    plt.show()

if __name__ == "__main__":
    # Ensure this matches the CSV filename generated by your previous script
    plot_news_price_alignment("experiment_aligned_2026.csv")